#!/bin/bash

battery_info=$(acpi -b)
battery_percent=$(echo "$battery_info" | grep -P -o '[0-9]+(?=%)')
charging_status=$(echo "$battery_info" | grep -o "Charging")

if [[ $charging_status ]]; then
    echo "$battery_percent%"
elif [[ $battery_percent -ge 0 && $battery_percent -lt 20 ]]; then
    echo " $battery_percent%"
elif [[ $battery_percent -ge 20 && $battery_percent -lt 40 ]]; then
    echo " $battery_percent%"
elif [[ $battery_percent -ge 40 && $battery_percent -lt 60 ]]; then
    echo " $battery_percent%"
elif [[ $battery_percent -ge 60 && $battery_percent -lt 80 ]]; then
    echo " $battery_percent%"
elif [[ $battery_percent -ge 80 && $battery_percent -le 100 ]]; then
    echo " $battery_percent%"
else
    echo " "
fi
